go: 1.5.4
repository:
    path: github.com/prometheus/node_exporter
build:
    ldflags: |
        -X main.Version={{.Version}}
        -X {{repoPath}}/collector.Version={{.Version}}
        -X {{repoPath}}/collector.Revision={{.Revision}}
        -X {{repoPath}}/collector.Branch={{.Branch}}
tarball:
    files:
        - LICENSE
        - NOTICE
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - darwin/amd64
        - darwin/386
        - windows/amd64
        - windows/386
        - netbsd/amd64
        - netbsd/386
        - linux/arm
        - linux/arm64
        - netbsd/arm
        - linux/ppc64le
