FROM golang:alpine

RUN apk add --update git

ENV GOPATH /go
ENV CGO_ENABLED=0

ARG ldflags=""

ADD . /go/src/github.com/prometheus/node_exporter
RUN go get -d github.com/prometheus/node_exporter
RUN go build -ldflags "${ldflags}" -o /bin/node_exporter github.com/prometheus/node_exporter


CMD /bin/cat

