---
version: 2.1
orbs:
  prometheus: prometheus/prometheus@0.17.1
executors:
  # Whenever the Go version is updated here, .promu.yml and .promu-cgo.yml
  # should also be updated.
  golang:
    docker:
      - image: cimg/go:1.26
  arm:
    docker:
      - image: cimg/go:1.26
    resource_class: arm.medium

jobs:
  test:
    executor: golang
    steps:
      - run: "true"

workflows:
  version: 2
  node_exporter:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
