{
 "title": "Node Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(node_exporter_build_info, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_exporter_build_info{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=~\"Node.+\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "avg by (instance) (1 - rate(node_cpu_seconds_total{cluster=\"$cluster\", mode=\"idle\"}[5m]))",
     "legendFormat": "{{instance}} (CPU)"
    }
   ]
  },
  {
   "title": "Top Nodes by CPU",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(10, avg by (instance) (1-rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[5m])))"
    }
   ]
  },
  {
   "title": "Top Nodes by Memory",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "topk(10, 1 - (node_memory_MemAvailable_bytes{cluster=\"$cluster\"} / node_memory_MemTotal_bytes{cluster=\"$cluster\"}))"
    }
   ]
  }
 ]
}