// Copyright 2024 The Prometheus Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type metric struct {
	name      string
	help      string
	subsystem string
	file      string
}

func main() {
	collectorDir := "collector"
	fset := token.NewFileSet()
	metrics := []metric{}

	absCollectorDir, _ := filepath.Abs(collectorDir)
	fmt.Fprintf(os.Stderr, "Searching in %s\n", absCollectorDir)

	err := filepath.Walk(absCollectorDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		f, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error parsing %s: %v\n", path, err)
			return nil
		}

		// First pass: find all constant strings that might be subsystems
		subsystems := make(map[string]string)
		ast.Inspect(f, func(n ast.Node) bool {
			if spec, ok := n.(*ast.ValueSpec); ok {
				for i, name := range spec.Names {
					if strings.HasSuffix(name.Name, "Subsystem") || name.Name == "subsystem" {
						if len(spec.Values) > i {
							if lit, ok := spec.Values[i].(*ast.BasicLit); ok {
								subsystems[name.Name] = strings.Trim(lit.Value, "\"")
							}
						}
					}
				}
			}
			return true
		})

		// Second pass: find NewDesc calls
		ast.Inspect(f, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}

			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok || sel.Sel.Name != "NewDesc" {
				return true
			}

			if len(call.Args) < 2 {
				return true
			}

			m := metric{file: path}

			// Extract Help string
			if lit, ok := call.Args[1].(*ast.BasicLit); ok {
				m.help = strings.Trim(lit.Value, "\"")
			} else if ident, ok := call.Args[1].(*ast.Ident); ok {
				// Search for the identifier's value
				ast.Inspect(f, func(n2 ast.Node) bool {
					if spec, ok := n2.(*ast.ValueSpec); ok {
						for i, name := range spec.Names {
							if name.Name == ident.Name {
								if len(spec.Values) > i {
									if lit, ok := spec.Values[i].(*ast.BasicLit); ok {
										m.help = strings.Trim(lit.Value, "\"")
									}
								}
							}
						}
					}
					return true
				})
			}

			// Extract Name
			if nameCall, ok := call.Args[0].(*ast.CallExpr); ok {
				// Case: prometheus.BuildFQName(namespace, subsystem, "name")
				if len(nameCall.Args) >= 3 {
					subsystem := ""
					if lit, ok := nameCall.Args[1].(*ast.BasicLit); ok {
						subsystem = strings.Trim(lit.Value, "\"")
					} else if ident, ok := nameCall.Args[1].(*ast.Ident); ok {
						subsystem = subsystems[ident.Name]
					} else if sel, ok := nameCall.Args[1].(*ast.SelectorExpr); ok {
						// Handle things like collector.Subsystem if they exist
						subsystem = sel.Sel.Name
					}

					if lit, ok := nameCall.Args[2].(*ast.BasicLit); ok {
						namePart := strings.Trim(lit.Value, "\"")
						if subsystem != "" {
							m.name = fmt.Sprintf("node_%s_%s", subsystem, namePart)
						} else {
							m.name = fmt.Sprintf("node_%s", namePart)
						}
					}
				}
			} else if lit, ok := call.Args[0].(*ast.BasicLit); ok {
				// Case: prometheus.NewDesc("metric_name", "help", ...)
				m.name = strings.Trim(lit.Value, "\"")
			}

			if m.name != "" && m.help != "" {
				metrics = append(metrics, m)
			}

			return true
		})

		return nil
	})

	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	if len(metrics) == 0 {
		fmt.Fprintf(os.Stderr, "No metrics found!\n")
		os.Exit(0)
	}

	sort.Slice(metrics, func(i, j int) bool {
		if metrics[i].name != metrics[j].name {
			return metrics[i].name < metrics[j].name
		}
		return metrics[i].file < metrics[j].file
	})

	// De-duplicate
	uniqueMetrics := []metric{}
	for i, m := range metrics {
		if i == 0 || m.name != metrics[i-1].name {
			uniqueMetrics = append(uniqueMetrics, m)
		}
	}

	fmt.Println("# Node Exporter Metrics")
	fmt.Println("\nThis file is auto-generated by `tools/doc_generator/main.go`.")
	fmt.Println("\n| Metric | Description | Collector |")
	fmt.Println("| --- | --- | --- |")
	for _, m := range uniqueMetrics {
		collector := strings.TrimSuffix(filepath.Base(m.file), ".go")
		if idx := strings.Index(collector, "_"); idx != -1 {
			collector = collector[:idx]
		}
		fmt.Printf("| %s | %s | %s |\n", m.name, m.help, collector)
	}
}
