// Code generated by netstat-descs; DO NOT EDIT.

//go:build !nonetstat

package collector

import (
	"github.com/prometheus/client_golang/prometheus"
)

// netStatMetricDescs returns the explicit, source-visible metric descriptors
// for every field of the procfs netstat/snmp/snmp6 statistics structs, keyed by
// "<Protocol>_<Field>". Descriptors are allocated once; collection looks them up
// by name instead of calling prometheus.NewDesc on every scrape.
func netStatMetricDescs() map[string]*prometheus.Desc {
	return map[string]*prometheus.Desc{
		"TcpExt_SyncookiesSent": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_SyncookiesSent"),
			"Statistic TcpExtSyncookiesSent.",
			nil, nil),
		"TcpExt_SyncookiesRecv": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_SyncookiesRecv"),
			"Statistic TcpExtSyncookiesRecv.",
			nil, nil),
		"TcpExt_SyncookiesFailed": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_SyncookiesFailed"),
			"Statistic TcpExtSyncookiesFailed.",
			nil, nil),
		"TcpExt_EmbryonicRsts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_EmbryonicRsts"),
			"Statistic TcpExtEmbryonicRsts.",
			nil, nil),
		"TcpExt_PruneCalled": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_PruneCalled"),
			"Statistic TcpExtPruneCalled.",
			nil, nil),
		"TcpExt_RcvPruned": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_RcvPruned"),
			"Statistic TcpExtRcvPruned.",
			nil, nil),
		"TcpExt_OfoPruned": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_OfoPruned"),
			"Statistic TcpExtOfoPruned.",
			nil, nil),
		"TcpExt_OutOfWindowIcmps": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_OutOfWindowIcmps"),
			"Statistic TcpExtOutOfWindowIcmps.",
			nil, nil),
		"TcpExt_LockDroppedIcmps": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_LockDroppedIcmps"),
			"Statistic TcpExtLockDroppedIcmps.",
			nil, nil),
		"TcpExt_ArpFilter": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_ArpFilter"),
			"Statistic TcpExtArpFilter.",
			nil, nil),
		"TcpExt_TW": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TW"),
			"Statistic TcpExtTW.",
			nil, nil),
		"TcpExt_TWRecycled": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TWRecycled"),
			"Statistic TcpExtTWRecycled.",
			nil, nil),
		"TcpExt_TWKilled": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TWKilled"),
			"Statistic TcpExtTWKilled.",
			nil, nil),
		"TcpExt_PAWSActive": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_PAWSActive"),
			"Statistic TcpExtPAWSActive.",
			nil, nil),
		"TcpExt_PAWSEstab": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_PAWSEstab"),
			"Statistic TcpExtPAWSEstab.",
			nil, nil),
		"TcpExt_DelayedACKs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_DelayedACKs"),
			"Statistic TcpExtDelayedACKs.",
			nil, nil),
		"TcpExt_DelayedACKLocked": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_DelayedACKLocked"),
			"Statistic TcpExtDelayedACKLocked.",
			nil, nil),
		"TcpExt_DelayedACKLost": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_DelayedACKLost"),
			"Statistic TcpExtDelayedACKLost.",
			nil, nil),
		"TcpExt_ListenOverflows": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_ListenOverflows"),
			"Statistic TcpExtListenOverflows.",
			nil, nil),
		"TcpExt_ListenDrops": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_ListenDrops"),
			"Statistic TcpExtListenDrops.",
			nil, nil),
		"TcpExt_TCPHPHits": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPHPHits"),
			"Statistic TcpExtTCPHPHits.",
			nil, nil),
		"TcpExt_TCPPureAcks": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPPureAcks"),
			"Statistic TcpExtTCPPureAcks.",
			nil, nil),
		"TcpExt_TCPHPAcks": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPHPAcks"),
			"Statistic TcpExtTCPHPAcks.",
			nil, nil),
		"TcpExt_TCPRenoRecovery": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPRenoRecovery"),
			"Statistic TcpExtTCPRenoRecovery.",
			nil, nil),
		"TcpExt_TCPSackRecovery": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSackRecovery"),
			"Statistic TcpExtTCPSackRecovery.",
			nil, nil),
		"TcpExt_TCPSACKReneging": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSACKReneging"),
			"Statistic TcpExtTCPSACKReneging.",
			nil, nil),
		"TcpExt_TCPSACKReorder": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSACKReorder"),
			"Statistic TcpExtTCPSACKReorder.",
			nil, nil),
		"TcpExt_TCPRenoReorder": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPRenoReorder"),
			"Statistic TcpExtTCPRenoReorder.",
			nil, nil),
		"TcpExt_TCPTSReorder": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPTSReorder"),
			"Statistic TcpExtTCPTSReorder.",
			nil, nil),
		"TcpExt_TCPFullUndo": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPFullUndo"),
			"Statistic TcpExtTCPFullUndo.",
			nil, nil),
		"TcpExt_TCPPartialUndo": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPPartialUndo"),
			"Statistic TcpExtTCPPartialUndo.",
			nil, nil),
		"TcpExt_TCPDSACKUndo": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPDSACKUndo"),
			"Statistic TcpExtTCPDSACKUndo.",
			nil, nil),
		"TcpExt_TCPLossUndo": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPLossUndo"),
			"Statistic TcpExtTCPLossUndo.",
			nil, nil),
		"TcpExt_TCPLostRetransmit": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPLostRetransmit"),
			"Statistic TcpExtTCPLostRetransmit.",
			nil, nil),
		"TcpExt_TCPRenoFailures": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPRenoFailures"),
			"Statistic TcpExtTCPRenoFailures.",
			nil, nil),
		"TcpExt_TCPSackFailures": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSackFailures"),
			"Statistic TcpExtTCPSackFailures.",
			nil, nil),
		"TcpExt_TCPLossFailures": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPLossFailures"),
			"Statistic TcpExtTCPLossFailures.",
			nil, nil),
		"TcpExt_TCPFastRetrans": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPFastRetrans"),
			"Statistic TcpExtTCPFastRetrans.",
			nil, nil),
		"TcpExt_TCPSlowStartRetrans": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSlowStartRetrans"),
			"Statistic TcpExtTCPSlowStartRetrans.",
			nil, nil),
		"TcpExt_TCPTimeouts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPTimeouts"),
			"Statistic TcpExtTCPTimeouts.",
			nil, nil),
		"TcpExt_TCPLossProbes": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPLossProbes"),
			"Statistic TcpExtTCPLossProbes.",
			nil, nil),
		"TcpExt_TCPLossProbeRecovery": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPLossProbeRecovery"),
			"Statistic TcpExtTCPLossProbeRecovery.",
			nil, nil),
		"TcpExt_TCPRenoRecoveryFail": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPRenoRecoveryFail"),
			"Statistic TcpExtTCPRenoRecoveryFail.",
			nil, nil),
		"TcpExt_TCPSackRecoveryFail": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSackRecoveryFail"),
			"Statistic TcpExtTCPSackRecoveryFail.",
			nil, nil),
		"TcpExt_TCPRcvCollapsed": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPRcvCollapsed"),
			"Statistic TcpExtTCPRcvCollapsed.",
			nil, nil),
		"TcpExt_TCPDSACKOldSent": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPDSACKOldSent"),
			"Statistic TcpExtTCPDSACKOldSent.",
			nil, nil),
		"TcpExt_TCPDSACKOfoSent": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPDSACKOfoSent"),
			"Statistic TcpExtTCPDSACKOfoSent.",
			nil, nil),
		"TcpExt_TCPDSACKRecv": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPDSACKRecv"),
			"Statistic TcpExtTCPDSACKRecv.",
			nil, nil),
		"TcpExt_TCPDSACKOfoRecv": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPDSACKOfoRecv"),
			"Statistic TcpExtTCPDSACKOfoRecv.",
			nil, nil),
		"TcpExt_TCPAbortOnData": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPAbortOnData"),
			"Statistic TcpExtTCPAbortOnData.",
			nil, nil),
		"TcpExt_TCPAbortOnClose": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPAbortOnClose"),
			"Statistic TcpExtTCPAbortOnClose.",
			nil, nil),
		"TcpExt_TCPAbortOnMemory": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPAbortOnMemory"),
			"Statistic TcpExtTCPAbortOnMemory.",
			nil, nil),
		"TcpExt_TCPAbortOnTimeout": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPAbortOnTimeout"),
			"Statistic TcpExtTCPAbortOnTimeout.",
			nil, nil),
		"TcpExt_TCPAbortOnLinger": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPAbortOnLinger"),
			"Statistic TcpExtTCPAbortOnLinger.",
			nil, nil),
		"TcpExt_TCPAbortFailed": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPAbortFailed"),
			"Statistic TcpExtTCPAbortFailed.",
			nil, nil),
		"TcpExt_TCPMemoryPressures": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPMemoryPressures"),
			"Statistic TcpExtTCPMemoryPressures.",
			nil, nil),
		"TcpExt_TCPMemoryPressuresChrono": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPMemoryPressuresChrono"),
			"Statistic TcpExtTCPMemoryPressuresChrono.",
			nil, nil),
		"TcpExt_TCPSACKDiscard": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSACKDiscard"),
			"Statistic TcpExtTCPSACKDiscard.",
			nil, nil),
		"TcpExt_TCPDSACKIgnoredOld": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPDSACKIgnoredOld"),
			"Statistic TcpExtTCPDSACKIgnoredOld.",
			nil, nil),
		"TcpExt_TCPDSACKIgnoredNoUndo": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPDSACKIgnoredNoUndo"),
			"Statistic TcpExtTCPDSACKIgnoredNoUndo.",
			nil, nil),
		"TcpExt_TCPSpuriousRTOs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSpuriousRTOs"),
			"Statistic TcpExtTCPSpuriousRTOs.",
			nil, nil),
		"TcpExt_TCPMD5NotFound": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPMD5NotFound"),
			"Statistic TcpExtTCPMD5NotFound.",
			nil, nil),
		"TcpExt_TCPMD5Unexpected": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPMD5Unexpected"),
			"Statistic TcpExtTCPMD5Unexpected.",
			nil, nil),
		"TcpExt_TCPMD5Failure": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPMD5Failure"),
			"Statistic TcpExtTCPMD5Failure.",
			nil, nil),
		"TcpExt_TCPSackShifted": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSackShifted"),
			"Statistic TcpExtTCPSackShifted.",
			nil, nil),
		"TcpExt_TCPSackMerged": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSackMerged"),
			"Statistic TcpExtTCPSackMerged.",
			nil, nil),
		"TcpExt_TCPSackShiftFallback": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSackShiftFallback"),
			"Statistic TcpExtTCPSackShiftFallback.",
			nil, nil),
		"TcpExt_TCPBacklogDrop": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPBacklogDrop"),
			"Statistic TcpExtTCPBacklogDrop.",
			nil, nil),
		"TcpExt_PFMemallocDrop": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_PFMemallocDrop"),
			"Statistic TcpExtPFMemallocDrop.",
			nil, nil),
		"TcpExt_TCPMinTTLDrop": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPMinTTLDrop"),
			"Statistic TcpExtTCPMinTTLDrop.",
			nil, nil),
		"TcpExt_TCPDeferAcceptDrop": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPDeferAcceptDrop"),
			"Statistic TcpExtTCPDeferAcceptDrop.",
			nil, nil),
		"TcpExt_IPReversePathFilter": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_IPReversePathFilter"),
			"Statistic TcpExtIPReversePathFilter.",
			nil, nil),
		"TcpExt_TCPTimeWaitOverflow": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPTimeWaitOverflow"),
			"Statistic TcpExtTCPTimeWaitOverflow.",
			nil, nil),
		"TcpExt_TCPReqQFullDoCookies": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPReqQFullDoCookies"),
			"Statistic TcpExtTCPReqQFullDoCookies.",
			nil, nil),
		"TcpExt_TCPReqQFullDrop": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPReqQFullDrop"),
			"Statistic TcpExtTCPReqQFullDrop.",
			nil, nil),
		"TcpExt_TCPRetransFail": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPRetransFail"),
			"Statistic TcpExtTCPRetransFail.",
			nil, nil),
		"TcpExt_TCPRcvCoalesce": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPRcvCoalesce"),
			"Statistic TcpExtTCPRcvCoalesce.",
			nil, nil),
		"TcpExt_TCPRcvQDrop": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPRcvQDrop"),
			"Statistic TcpExtTCPRcvQDrop.",
			nil, nil),
		"TcpExt_TCPOFOQueue": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPOFOQueue"),
			"Statistic TcpExtTCPOFOQueue.",
			nil, nil),
		"TcpExt_TCPOFODrop": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPOFODrop"),
			"Statistic TcpExtTCPOFODrop.",
			nil, nil),
		"TcpExt_TCPOFOMerge": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPOFOMerge"),
			"Statistic TcpExtTCPOFOMerge.",
			nil, nil),
		"TcpExt_TCPChallengeACK": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPChallengeACK"),
			"Statistic TcpExtTCPChallengeACK.",
			nil, nil),
		"TcpExt_TCPSYNChallenge": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSYNChallenge"),
			"Statistic TcpExtTCPSYNChallenge.",
			nil, nil),
		"TcpExt_TCPFastOpenActive": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPFastOpenActive"),
			"Statistic TcpExtTCPFastOpenActive.",
			nil, nil),
		"TcpExt_TCPFastOpenActiveFail": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPFastOpenActiveFail"),
			"Statistic TcpExtTCPFastOpenActiveFail.",
			nil, nil),
		"TcpExt_TCPFastOpenPassive": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPFastOpenPassive"),
			"Statistic TcpExtTCPFastOpenPassive.",
			nil, nil),
		"TcpExt_TCPFastOpenPassiveFail": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPFastOpenPassiveFail"),
			"Statistic TcpExtTCPFastOpenPassiveFail.",
			nil, nil),
		"TcpExt_TCPFastOpenListenOverflow": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPFastOpenListenOverflow"),
			"Statistic TcpExtTCPFastOpenListenOverflow.",
			nil, nil),
		"TcpExt_TCPFastOpenCookieReqd": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPFastOpenCookieReqd"),
			"Statistic TcpExtTCPFastOpenCookieReqd.",
			nil, nil),
		"TcpExt_TCPFastOpenBlackhole": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPFastOpenBlackhole"),
			"Statistic TcpExtTCPFastOpenBlackhole.",
			nil, nil),
		"TcpExt_TCPSpuriousRtxHostQueues": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSpuriousRtxHostQueues"),
			"Statistic TcpExtTCPSpuriousRtxHostQueues.",
			nil, nil),
		"TcpExt_BusyPollRxPackets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_BusyPollRxPackets"),
			"Statistic TcpExtBusyPollRxPackets.",
			nil, nil),
		"TcpExt_TCPAutoCorking": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPAutoCorking"),
			"Statistic TcpExtTCPAutoCorking.",
			nil, nil),
		"TcpExt_TCPFromZeroWindowAdv": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPFromZeroWindowAdv"),
			"Statistic TcpExtTCPFromZeroWindowAdv.",
			nil, nil),
		"TcpExt_TCPToZeroWindowAdv": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPToZeroWindowAdv"),
			"Statistic TcpExtTCPToZeroWindowAdv.",
			nil, nil),
		"TcpExt_TCPWantZeroWindowAdv": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPWantZeroWindowAdv"),
			"Statistic TcpExtTCPWantZeroWindowAdv.",
			nil, nil),
		"TcpExt_TCPSynRetrans": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSynRetrans"),
			"Statistic TcpExtTCPSynRetrans.",
			nil, nil),
		"TcpExt_TCPOrigDataSent": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPOrigDataSent"),
			"Statistic TcpExtTCPOrigDataSent.",
			nil, nil),
		"TcpExt_TCPHystartTrainDetect": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPHystartTrainDetect"),
			"Statistic TcpExtTCPHystartTrainDetect.",
			nil, nil),
		"TcpExt_TCPHystartTrainCwnd": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPHystartTrainCwnd"),
			"Statistic TcpExtTCPHystartTrainCwnd.",
			nil, nil),
		"TcpExt_TCPHystartDelayDetect": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPHystartDelayDetect"),
			"Statistic TcpExtTCPHystartDelayDetect.",
			nil, nil),
		"TcpExt_TCPHystartDelayCwnd": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPHystartDelayCwnd"),
			"Statistic TcpExtTCPHystartDelayCwnd.",
			nil, nil),
		"TcpExt_TCPACKSkippedSynRecv": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPACKSkippedSynRecv"),
			"Statistic TcpExtTCPACKSkippedSynRecv.",
			nil, nil),
		"TcpExt_TCPACKSkippedPAWS": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPACKSkippedPAWS"),
			"Statistic TcpExtTCPACKSkippedPAWS.",
			nil, nil),
		"TcpExt_TCPACKSkippedSeq": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPACKSkippedSeq"),
			"Statistic TcpExtTCPACKSkippedSeq.",
			nil, nil),
		"TcpExt_TCPACKSkippedFinWait2": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPACKSkippedFinWait2"),
			"Statistic TcpExtTCPACKSkippedFinWait2.",
			nil, nil),
		"TcpExt_TCPACKSkippedTimeWait": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPACKSkippedTimeWait"),
			"Statistic TcpExtTCPACKSkippedTimeWait.",
			nil, nil),
		"TcpExt_TCPACKSkippedChallenge": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPACKSkippedChallenge"),
			"Statistic TcpExtTCPACKSkippedChallenge.",
			nil, nil),
		"TcpExt_TCPWinProbe": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPWinProbe"),
			"Statistic TcpExtTCPWinProbe.",
			nil, nil),
		"TcpExt_TCPKeepAlive": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPKeepAlive"),
			"Statistic TcpExtTCPKeepAlive.",
			nil, nil),
		"TcpExt_TCPMTUPFail": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPMTUPFail"),
			"Statistic TcpExtTCPMTUPFail.",
			nil, nil),
		"TcpExt_TCPMTUPSuccess": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPMTUPSuccess"),
			"Statistic TcpExtTCPMTUPSuccess.",
			nil, nil),
		"TcpExt_TCPWqueueTooBig": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPWqueueTooBig"),
			"Statistic TcpExtTCPWqueueTooBig.",
			nil, nil),
		"TcpExt_TCPLoss": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPLoss"),
			"Statistic TcpExtTCPLoss.",
			nil, nil),
		"TcpExt_PAWSPassive": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_PAWSPassive"),
			"Statistic TcpExtPAWSPassive.",
			nil, nil),
		"TcpExt_TCPForwardRetrans": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPForwardRetrans"),
			"Statistic TcpExtTCPForwardRetrans.",
			nil, nil),
		"TcpExt_TCPSchedulerFailed": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPSchedulerFailed"),
			"Statistic TcpExtTCPSchedulerFailed.",
			nil, nil),
		"TcpExt_TCPPrequeued": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPPrequeued"),
			"Statistic TcpExtTCPPrequeued.",
			nil, nil),
		"TcpExt_TCPDirectCopyFromBacklog": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPDirectCopyFromBacklog"),
			"Statistic TcpExtTCPDirectCopyFromBacklog.",
			nil, nil),
		"TcpExt_TCPDirectCopyFromPrequeue": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPDirectCopyFromPrequeue"),
			"Statistic TcpExtTCPDirectCopyFromPrequeue.",
			nil, nil),
		"TcpExt_TCPPrequeueDropped": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPPrequeueDropped"),
			"Statistic TcpExtTCPPrequeueDropped.",
			nil, nil),
		"TcpExt_TCPFACKReorder": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPFACKReorder"),
			"Statistic TcpExtTCPFACKReorder.",
			nil, nil),
		"TcpExt_TCPHPHitsToUser": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "TcpExt_TCPHPHitsToUser"),
			"Statistic TcpExtTCPHPHitsToUser.",
			nil, nil),
		"IpExt_InNoRoutes": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_InNoRoutes"),
			"Statistic IpExtInNoRoutes.",
			nil, nil),
		"IpExt_InTruncatedPkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_InTruncatedPkts"),
			"Statistic IpExtInTruncatedPkts.",
			nil, nil),
		"IpExt_InMcastPkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_InMcastPkts"),
			"Statistic IpExtInMcastPkts.",
			nil, nil),
		"IpExt_OutMcastPkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_OutMcastPkts"),
			"Statistic IpExtOutMcastPkts.",
			nil, nil),
		"IpExt_InBcastPkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_InBcastPkts"),
			"Statistic IpExtInBcastPkts.",
			nil, nil),
		"IpExt_OutBcastPkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_OutBcastPkts"),
			"Statistic IpExtOutBcastPkts.",
			nil, nil),
		"IpExt_InOctets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_InOctets"),
			"Statistic IpExtInOctets.",
			nil, nil),
		"IpExt_OutOctets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_OutOctets"),
			"Statistic IpExtOutOctets.",
			nil, nil),
		"IpExt_InMcastOctets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_InMcastOctets"),
			"Statistic IpExtInMcastOctets.",
			nil, nil),
		"IpExt_OutMcastOctets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_OutMcastOctets"),
			"Statistic IpExtOutMcastOctets.",
			nil, nil),
		"IpExt_InBcastOctets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_InBcastOctets"),
			"Statistic IpExtInBcastOctets.",
			nil, nil),
		"IpExt_OutBcastOctets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_OutBcastOctets"),
			"Statistic IpExtOutBcastOctets.",
			nil, nil),
		"IpExt_InCsumErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_InCsumErrors"),
			"Statistic IpExtInCsumErrors.",
			nil, nil),
		"IpExt_InNoECTPkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_InNoECTPkts"),
			"Statistic IpExtInNoECTPkts.",
			nil, nil),
		"IpExt_InECT1Pkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_InECT1Pkts"),
			"Statistic IpExtInECT1Pkts.",
			nil, nil),
		"IpExt_InECT0Pkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_InECT0Pkts"),
			"Statistic IpExtInECT0Pkts.",
			nil, nil),
		"IpExt_InCEPkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_InCEPkts"),
			"Statistic IpExtInCEPkts.",
			nil, nil),
		"IpExt_ReasmOverlaps": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IpExt_ReasmOverlaps"),
			"Statistic IpExtReasmOverlaps.",
			nil, nil),
		"Ip_Forwarding": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_Forwarding"),
			"Statistic IpForwarding.",
			nil, nil),
		"Ip_DefaultTTL": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_DefaultTTL"),
			"Statistic IpDefaultTTL.",
			nil, nil),
		"Ip_InReceives": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_InReceives"),
			"Statistic IpInReceives.",
			nil, nil),
		"Ip_InHdrErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_InHdrErrors"),
			"Statistic IpInHdrErrors.",
			nil, nil),
		"Ip_InAddrErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_InAddrErrors"),
			"Statistic IpInAddrErrors.",
			nil, nil),
		"Ip_ForwDatagrams": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_ForwDatagrams"),
			"Statistic IpForwDatagrams.",
			nil, nil),
		"Ip_InUnknownProtos": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_InUnknownProtos"),
			"Statistic IpInUnknownProtos.",
			nil, nil),
		"Ip_InDiscards": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_InDiscards"),
			"Statistic IpInDiscards.",
			nil, nil),
		"Ip_InDelivers": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_InDelivers"),
			"Statistic IpInDelivers.",
			nil, nil),
		"Ip_OutRequests": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_OutRequests"),
			"Statistic IpOutRequests.",
			nil, nil),
		"Ip_OutDiscards": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_OutDiscards"),
			"Statistic IpOutDiscards.",
			nil, nil),
		"Ip_OutNoRoutes": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_OutNoRoutes"),
			"Statistic IpOutNoRoutes.",
			nil, nil),
		"Ip_ReasmTimeout": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_ReasmTimeout"),
			"Statistic IpReasmTimeout.",
			nil, nil),
		"Ip_ReasmReqds": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_ReasmReqds"),
			"Statistic IpReasmReqds.",
			nil, nil),
		"Ip_ReasmOKs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_ReasmOKs"),
			"Statistic IpReasmOKs.",
			nil, nil),
		"Ip_ReasmFails": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_ReasmFails"),
			"Statistic IpReasmFails.",
			nil, nil),
		"Ip_FragOKs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_FragOKs"),
			"Statistic IpFragOKs.",
			nil, nil),
		"Ip_FragFails": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_FragFails"),
			"Statistic IpFragFails.",
			nil, nil),
		"Ip_FragCreates": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip_FragCreates"),
			"Statistic IpFragCreates.",
			nil, nil),
		"Icmp_InMsgs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InMsgs"),
			"Statistic IcmpInMsgs.",
			nil, nil),
		"Icmp_InErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InErrors"),
			"Statistic IcmpInErrors.",
			nil, nil),
		"Icmp_InCsumErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InCsumErrors"),
			"Statistic IcmpInCsumErrors.",
			nil, nil),
		"Icmp_InDestUnreachs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InDestUnreachs"),
			"Statistic IcmpInDestUnreachs.",
			nil, nil),
		"Icmp_InTimeExcds": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InTimeExcds"),
			"Statistic IcmpInTimeExcds.",
			nil, nil),
		"Icmp_InParmProbs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InParmProbs"),
			"Statistic IcmpInParmProbs.",
			nil, nil),
		"Icmp_InSrcQuenchs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InSrcQuenchs"),
			"Statistic IcmpInSrcQuenchs.",
			nil, nil),
		"Icmp_InRedirects": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InRedirects"),
			"Statistic IcmpInRedirects.",
			nil, nil),
		"Icmp_InEchos": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InEchos"),
			"Statistic IcmpInEchos.",
			nil, nil),
		"Icmp_InEchoReps": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InEchoReps"),
			"Statistic IcmpInEchoReps.",
			nil, nil),
		"Icmp_InTimestamps": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InTimestamps"),
			"Statistic IcmpInTimestamps.",
			nil, nil),
		"Icmp_InTimestampReps": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InTimestampReps"),
			"Statistic IcmpInTimestampReps.",
			nil, nil),
		"Icmp_InAddrMasks": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InAddrMasks"),
			"Statistic IcmpInAddrMasks.",
			nil, nil),
		"Icmp_InAddrMaskReps": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_InAddrMaskReps"),
			"Statistic IcmpInAddrMaskReps.",
			nil, nil),
		"Icmp_OutMsgs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutMsgs"),
			"Statistic IcmpOutMsgs.",
			nil, nil),
		"Icmp_OutErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutErrors"),
			"Statistic IcmpOutErrors.",
			nil, nil),
		"Icmp_OutDestUnreachs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutDestUnreachs"),
			"Statistic IcmpOutDestUnreachs.",
			nil, nil),
		"Icmp_OutTimeExcds": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutTimeExcds"),
			"Statistic IcmpOutTimeExcds.",
			nil, nil),
		"Icmp_OutParmProbs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutParmProbs"),
			"Statistic IcmpOutParmProbs.",
			nil, nil),
		"Icmp_OutSrcQuenchs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutSrcQuenchs"),
			"Statistic IcmpOutSrcQuenchs.",
			nil, nil),
		"Icmp_OutRedirects": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutRedirects"),
			"Statistic IcmpOutRedirects.",
			nil, nil),
		"Icmp_OutEchos": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutEchos"),
			"Statistic IcmpOutEchos.",
			nil, nil),
		"Icmp_OutEchoReps": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutEchoReps"),
			"Statistic IcmpOutEchoReps.",
			nil, nil),
		"Icmp_OutTimestamps": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutTimestamps"),
			"Statistic IcmpOutTimestamps.",
			nil, nil),
		"Icmp_OutTimestampReps": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutTimestampReps"),
			"Statistic IcmpOutTimestampReps.",
			nil, nil),
		"Icmp_OutAddrMasks": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutAddrMasks"),
			"Statistic IcmpOutAddrMasks.",
			nil, nil),
		"Icmp_OutAddrMaskReps": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp_OutAddrMaskReps"),
			"Statistic IcmpOutAddrMaskReps.",
			nil, nil),
		"IcmpMsg_InType3": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IcmpMsg_InType3"),
			"Statistic IcmpMsgInType3.",
			nil, nil),
		"IcmpMsg_OutType3": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "IcmpMsg_OutType3"),
			"Statistic IcmpMsgOutType3.",
			nil, nil),
		"Tcp_RtoAlgorithm": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_RtoAlgorithm"),
			"Statistic TcpRtoAlgorithm.",
			nil, nil),
		"Tcp_RtoMin": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_RtoMin"),
			"Statistic TcpRtoMin.",
			nil, nil),
		"Tcp_RtoMax": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_RtoMax"),
			"Statistic TcpRtoMax.",
			nil, nil),
		"Tcp_MaxConn": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_MaxConn"),
			"Statistic TcpMaxConn.",
			nil, nil),
		"Tcp_ActiveOpens": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_ActiveOpens"),
			"Statistic TcpActiveOpens.",
			nil, nil),
		"Tcp_PassiveOpens": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_PassiveOpens"),
			"Statistic TcpPassiveOpens.",
			nil, nil),
		"Tcp_AttemptFails": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_AttemptFails"),
			"Statistic TcpAttemptFails.",
			nil, nil),
		"Tcp_EstabResets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_EstabResets"),
			"Statistic TcpEstabResets.",
			nil, nil),
		"Tcp_CurrEstab": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_CurrEstab"),
			"Statistic TcpCurrEstab.",
			nil, nil),
		"Tcp_InSegs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_InSegs"),
			"Statistic TcpInSegs.",
			nil, nil),
		"Tcp_OutSegs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_OutSegs"),
			"Statistic TcpOutSegs.",
			nil, nil),
		"Tcp_RetransSegs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_RetransSegs"),
			"Statistic TcpRetransSegs.",
			nil, nil),
		"Tcp_InErrs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_InErrs"),
			"Statistic TcpInErrs.",
			nil, nil),
		"Tcp_OutRsts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_OutRsts"),
			"Statistic TcpOutRsts.",
			nil, nil),
		"Tcp_InCsumErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Tcp_InCsumErrors"),
			"Statistic TcpInCsumErrors.",
			nil, nil),
		"Udp_InDatagrams": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp_InDatagrams"),
			"Statistic UdpInDatagrams.",
			nil, nil),
		"Udp_NoPorts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp_NoPorts"),
			"Statistic UdpNoPorts.",
			nil, nil),
		"Udp_InErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp_InErrors"),
			"Statistic UdpInErrors.",
			nil, nil),
		"Udp_OutDatagrams": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp_OutDatagrams"),
			"Statistic UdpOutDatagrams.",
			nil, nil),
		"Udp_RcvbufErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp_RcvbufErrors"),
			"Statistic UdpRcvbufErrors.",
			nil, nil),
		"Udp_SndbufErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp_SndbufErrors"),
			"Statistic UdpSndbufErrors.",
			nil, nil),
		"Udp_InCsumErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp_InCsumErrors"),
			"Statistic UdpInCsumErrors.",
			nil, nil),
		"Udp_IgnoredMulti": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp_IgnoredMulti"),
			"Statistic UdpIgnoredMulti.",
			nil, nil),
		"UdpLite_InDatagrams": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite_InDatagrams"),
			"Statistic UdpLiteInDatagrams.",
			nil, nil),
		"UdpLite_NoPorts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite_NoPorts"),
			"Statistic UdpLiteNoPorts.",
			nil, nil),
		"UdpLite_InErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite_InErrors"),
			"Statistic UdpLiteInErrors.",
			nil, nil),
		"UdpLite_OutDatagrams": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite_OutDatagrams"),
			"Statistic UdpLiteOutDatagrams.",
			nil, nil),
		"UdpLite_RcvbufErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite_RcvbufErrors"),
			"Statistic UdpLiteRcvbufErrors.",
			nil, nil),
		"UdpLite_SndbufErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite_SndbufErrors"),
			"Statistic UdpLiteSndbufErrors.",
			nil, nil),
		"UdpLite_InCsumErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite_InCsumErrors"),
			"Statistic UdpLiteInCsumErrors.",
			nil, nil),
		"UdpLite_IgnoredMulti": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite_IgnoredMulti"),
			"Statistic UdpLiteIgnoredMulti.",
			nil, nil),
		"Ip6_InReceives": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InReceives"),
			"Statistic Ip6InReceives.",
			nil, nil),
		"Ip6_InHdrErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InHdrErrors"),
			"Statistic Ip6InHdrErrors.",
			nil, nil),
		"Ip6_InTooBigErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InTooBigErrors"),
			"Statistic Ip6InTooBigErrors.",
			nil, nil),
		"Ip6_InNoRoutes": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InNoRoutes"),
			"Statistic Ip6InNoRoutes.",
			nil, nil),
		"Ip6_InAddrErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InAddrErrors"),
			"Statistic Ip6InAddrErrors.",
			nil, nil),
		"Ip6_InUnknownProtos": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InUnknownProtos"),
			"Statistic Ip6InUnknownProtos.",
			nil, nil),
		"Ip6_InTruncatedPkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InTruncatedPkts"),
			"Statistic Ip6InTruncatedPkts.",
			nil, nil),
		"Ip6_InDiscards": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InDiscards"),
			"Statistic Ip6InDiscards.",
			nil, nil),
		"Ip6_InDelivers": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InDelivers"),
			"Statistic Ip6InDelivers.",
			nil, nil),
		"Ip6_OutForwDatagrams": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_OutForwDatagrams"),
			"Statistic Ip6OutForwDatagrams.",
			nil, nil),
		"Ip6_OutRequests": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_OutRequests"),
			"Statistic Ip6OutRequests.",
			nil, nil),
		"Ip6_OutDiscards": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_OutDiscards"),
			"Statistic Ip6OutDiscards.",
			nil, nil),
		"Ip6_OutNoRoutes": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_OutNoRoutes"),
			"Statistic Ip6OutNoRoutes.",
			nil, nil),
		"Ip6_ReasmTimeout": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_ReasmTimeout"),
			"Statistic Ip6ReasmTimeout.",
			nil, nil),
		"Ip6_ReasmReqds": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_ReasmReqds"),
			"Statistic Ip6ReasmReqds.",
			nil, nil),
		"Ip6_ReasmOKs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_ReasmOKs"),
			"Statistic Ip6ReasmOKs.",
			nil, nil),
		"Ip6_ReasmFails": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_ReasmFails"),
			"Statistic Ip6ReasmFails.",
			nil, nil),
		"Ip6_FragOKs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_FragOKs"),
			"Statistic Ip6FragOKs.",
			nil, nil),
		"Ip6_FragFails": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_FragFails"),
			"Statistic Ip6FragFails.",
			nil, nil),
		"Ip6_FragCreates": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_FragCreates"),
			"Statistic Ip6FragCreates.",
			nil, nil),
		"Ip6_InMcastPkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InMcastPkts"),
			"Statistic Ip6InMcastPkts.",
			nil, nil),
		"Ip6_OutMcastPkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_OutMcastPkts"),
			"Statistic Ip6OutMcastPkts.",
			nil, nil),
		"Ip6_InOctets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InOctets"),
			"Statistic Ip6InOctets.",
			nil, nil),
		"Ip6_OutOctets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_OutOctets"),
			"Statistic Ip6OutOctets.",
			nil, nil),
		"Ip6_InMcastOctets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InMcastOctets"),
			"Statistic Ip6InMcastOctets.",
			nil, nil),
		"Ip6_OutMcastOctets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_OutMcastOctets"),
			"Statistic Ip6OutMcastOctets.",
			nil, nil),
		"Ip6_InBcastOctets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InBcastOctets"),
			"Statistic Ip6InBcastOctets.",
			nil, nil),
		"Ip6_OutBcastOctets": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_OutBcastOctets"),
			"Statistic Ip6OutBcastOctets.",
			nil, nil),
		"Ip6_InNoECTPkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InNoECTPkts"),
			"Statistic Ip6InNoECTPkts.",
			nil, nil),
		"Ip6_InECT1Pkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InECT1Pkts"),
			"Statistic Ip6InECT1Pkts.",
			nil, nil),
		"Ip6_InECT0Pkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InECT0Pkts"),
			"Statistic Ip6InECT0Pkts.",
			nil, nil),
		"Ip6_InCEPkts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Ip6_InCEPkts"),
			"Statistic Ip6InCEPkts.",
			nil, nil),
		"Icmp6_InMsgs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InMsgs"),
			"Statistic Icmp6InMsgs.",
			nil, nil),
		"Icmp6_InErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InErrors"),
			"Statistic Icmp6InErrors.",
			nil, nil),
		"Icmp6_OutMsgs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutMsgs"),
			"Statistic Icmp6OutMsgs.",
			nil, nil),
		"Icmp6_OutErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutErrors"),
			"Statistic Icmp6OutErrors.",
			nil, nil),
		"Icmp6_InCsumErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InCsumErrors"),
			"Statistic Icmp6InCsumErrors.",
			nil, nil),
		"Icmp6_InDestUnreachs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InDestUnreachs"),
			"Statistic Icmp6InDestUnreachs.",
			nil, nil),
		"Icmp6_InPktTooBigs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InPktTooBigs"),
			"Statistic Icmp6InPktTooBigs.",
			nil, nil),
		"Icmp6_InTimeExcds": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InTimeExcds"),
			"Statistic Icmp6InTimeExcds.",
			nil, nil),
		"Icmp6_InParmProblems": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InParmProblems"),
			"Statistic Icmp6InParmProblems.",
			nil, nil),
		"Icmp6_InEchos": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InEchos"),
			"Statistic Icmp6InEchos.",
			nil, nil),
		"Icmp6_InEchoReplies": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InEchoReplies"),
			"Statistic Icmp6InEchoReplies.",
			nil, nil),
		"Icmp6_InGroupMembQueries": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InGroupMembQueries"),
			"Statistic Icmp6InGroupMembQueries.",
			nil, nil),
		"Icmp6_InGroupMembResponses": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InGroupMembResponses"),
			"Statistic Icmp6InGroupMembResponses.",
			nil, nil),
		"Icmp6_InGroupMembReductions": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InGroupMembReductions"),
			"Statistic Icmp6InGroupMembReductions.",
			nil, nil),
		"Icmp6_InRouterSolicits": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InRouterSolicits"),
			"Statistic Icmp6InRouterSolicits.",
			nil, nil),
		"Icmp6_InRouterAdvertisements": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InRouterAdvertisements"),
			"Statistic Icmp6InRouterAdvertisements.",
			nil, nil),
		"Icmp6_InNeighborSolicits": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InNeighborSolicits"),
			"Statistic Icmp6InNeighborSolicits.",
			nil, nil),
		"Icmp6_InNeighborAdvertisements": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InNeighborAdvertisements"),
			"Statistic Icmp6InNeighborAdvertisements.",
			nil, nil),
		"Icmp6_InRedirects": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InRedirects"),
			"Statistic Icmp6InRedirects.",
			nil, nil),
		"Icmp6_InMLDv2Reports": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InMLDv2Reports"),
			"Statistic Icmp6InMLDv2Reports.",
			nil, nil),
		"Icmp6_OutDestUnreachs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutDestUnreachs"),
			"Statistic Icmp6OutDestUnreachs.",
			nil, nil),
		"Icmp6_OutPktTooBigs": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutPktTooBigs"),
			"Statistic Icmp6OutPktTooBigs.",
			nil, nil),
		"Icmp6_OutTimeExcds": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutTimeExcds"),
			"Statistic Icmp6OutTimeExcds.",
			nil, nil),
		"Icmp6_OutParmProblems": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutParmProblems"),
			"Statistic Icmp6OutParmProblems.",
			nil, nil),
		"Icmp6_OutEchos": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutEchos"),
			"Statistic Icmp6OutEchos.",
			nil, nil),
		"Icmp6_OutEchoReplies": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutEchoReplies"),
			"Statistic Icmp6OutEchoReplies.",
			nil, nil),
		"Icmp6_OutGroupMembQueries": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutGroupMembQueries"),
			"Statistic Icmp6OutGroupMembQueries.",
			nil, nil),
		"Icmp6_OutGroupMembResponses": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutGroupMembResponses"),
			"Statistic Icmp6OutGroupMembResponses.",
			nil, nil),
		"Icmp6_OutGroupMembReductions": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutGroupMembReductions"),
			"Statistic Icmp6OutGroupMembReductions.",
			nil, nil),
		"Icmp6_OutRouterSolicits": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutRouterSolicits"),
			"Statistic Icmp6OutRouterSolicits.",
			nil, nil),
		"Icmp6_OutRouterAdvertisements": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutRouterAdvertisements"),
			"Statistic Icmp6OutRouterAdvertisements.",
			nil, nil),
		"Icmp6_OutNeighborSolicits": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutNeighborSolicits"),
			"Statistic Icmp6OutNeighborSolicits.",
			nil, nil),
		"Icmp6_OutNeighborAdvertisements": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutNeighborAdvertisements"),
			"Statistic Icmp6OutNeighborAdvertisements.",
			nil, nil),
		"Icmp6_OutRedirects": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutRedirects"),
			"Statistic Icmp6OutRedirects.",
			nil, nil),
		"Icmp6_OutMLDv2Reports": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutMLDv2Reports"),
			"Statistic Icmp6OutMLDv2Reports.",
			nil, nil),
		"Icmp6_InType1": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InType1"),
			"Statistic Icmp6InType1.",
			nil, nil),
		"Icmp6_InType134": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InType134"),
			"Statistic Icmp6InType134.",
			nil, nil),
		"Icmp6_InType135": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InType135"),
			"Statistic Icmp6InType135.",
			nil, nil),
		"Icmp6_InType136": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InType136"),
			"Statistic Icmp6InType136.",
			nil, nil),
		"Icmp6_InType143": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_InType143"),
			"Statistic Icmp6InType143.",
			nil, nil),
		"Icmp6_OutType133": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutType133"),
			"Statistic Icmp6OutType133.",
			nil, nil),
		"Icmp6_OutType135": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutType135"),
			"Statistic Icmp6OutType135.",
			nil, nil),
		"Icmp6_OutType136": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutType136"),
			"Statistic Icmp6OutType136.",
			nil, nil),
		"Icmp6_OutType143": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Icmp6_OutType143"),
			"Statistic Icmp6OutType143.",
			nil, nil),
		"Udp6_InDatagrams": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp6_InDatagrams"),
			"Statistic Udp6InDatagrams.",
			nil, nil),
		"Udp6_NoPorts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp6_NoPorts"),
			"Statistic Udp6NoPorts.",
			nil, nil),
		"Udp6_InErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp6_InErrors"),
			"Statistic Udp6InErrors.",
			nil, nil),
		"Udp6_OutDatagrams": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp6_OutDatagrams"),
			"Statistic Udp6OutDatagrams.",
			nil, nil),
		"Udp6_RcvbufErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp6_RcvbufErrors"),
			"Statistic Udp6RcvbufErrors.",
			nil, nil),
		"Udp6_SndbufErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp6_SndbufErrors"),
			"Statistic Udp6SndbufErrors.",
			nil, nil),
		"Udp6_InCsumErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp6_InCsumErrors"),
			"Statistic Udp6InCsumErrors.",
			nil, nil),
		"Udp6_IgnoredMulti": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "Udp6_IgnoredMulti"),
			"Statistic Udp6IgnoredMulti.",
			nil, nil),
		"UdpLite6_InDatagrams": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite6_InDatagrams"),
			"Statistic UdpLite6InDatagrams.",
			nil, nil),
		"UdpLite6_NoPorts": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite6_NoPorts"),
			"Statistic UdpLite6NoPorts.",
			nil, nil),
		"UdpLite6_InErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite6_InErrors"),
			"Statistic UdpLite6InErrors.",
			nil, nil),
		"UdpLite6_OutDatagrams": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite6_OutDatagrams"),
			"Statistic UdpLite6OutDatagrams.",
			nil, nil),
		"UdpLite6_RcvbufErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite6_RcvbufErrors"),
			"Statistic UdpLite6RcvbufErrors.",
			nil, nil),
		"UdpLite6_SndbufErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite6_SndbufErrors"),
			"Statistic UdpLite6SndbufErrors.",
			nil, nil),
		"UdpLite6_InCsumErrors": prometheus.NewDesc(
			prometheus.BuildFQName(namespace, netStatsSubsystem, "UdpLite6_InCsumErrors"),
			"Statistic UdpLite6InCsumErrors.",
			nil, nil),
	}
}
